lib/timerobot/web/router.ex
defmodule Timerobot.Web.Router do
  use Timerobot.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :login_required do
    plug Guardian.Plug.EnsureAuthenticated,
        handler: Timerobot.GuardianErrorHandler
  end

  pipeline :with_session do
    plug Guardian.Plug.VerifySession
    plug Guardian.Plug.LoadResource
    plug Timerobot.CurrentUser
  end

  scope "/", Timerobot.Web do
    pipe_through [:browser, :with_session]

    get "/", PageController, :index

    resources "/session", SessionController, only: [:new, :create, :delete]

    scope "/" do
      pipe_through :login_required

      resources "/people", PersonController, param: "slug"
      resources "/clients", ClientController, param: "slug"
      resources "/projects", ProjectController, param: "slug"
      resources "/times", EntryController

      get "/report", ReportController, :report
    end
  end
end

lib/timerobot/web/views/layout_view.ex
defmodule Timerobot.Web.LayoutView do
  use Timerobot.Web, :view

  def calculate_totals(times) do
    times
    |> Enum.reduce(0, fn({_date, _person, hours}, sum) -> sum + hours end)
  end

  def calculate_days(times) do
    hours = calculate_totals(times)
    hours_in_day = 8
    days = hours/hours_in_day
    Float.ceil(days * 4) / 4
  end

  def daily_hours(beginning_of_week, times) do
    0..6
    |> Enum.map(fn(day_offset) ->
      day = Timex.shift(beginning_of_week, days: day_offset)
      hours =
        times
        |> Enum.filter(fn({date, _person, _hours}) -> date == day end)
        |> Enum.reduce(0, fn({_date, _person, hours}, sum) -> sum + hours end)
      {day, hours}
    end)
  end
end

lib/timerobot/web/templates/layout/_header.html.eex
<header id="header" role="banner">
  <nav role="navigation" class="navbar navbar-inverse">
    <ul class="nav nav-pills pull-left">
      <li class="navlink">
        <%= link "Home", to: page_path(@conn, :index)%>
      </li>
      <li class="navlink">
        <%= link "People", to: person_path(@conn, :index) %>
      </li>
      <li class="navlink">
        <%= link "Clients", to: client_path(@conn, :index) %>
      </li>
      <li class="navlink">
        <%= link "Projects", to: project_path(@conn, :index) %>
      </li>
      <li class="navlink">
        <%= link "Entries", to: entry_path(@conn, :index) %>
      </li>
      <li class="navlink">
        <%= link "Report", to: report_path(@conn, :report) %>
      </li>
    </ul>
    <ul class="nav nav-pills pull-right">
      <%= if @current_user do %>
        <li class="navlink">
          <%= link "Sign out", to: session_path(@conn, :delete,
                                                @current_user),
                                                method: :delete %>
        </li>
      <% else %>
        <li class="navlink">
          <%= link "Sign in", to: session_path(@conn, :new) %>
        </li>
      <% end %>
    </ul>
  </nav>
</header>

lib/timerobot/web/templates/layout/_project_breakdown.html.eex
<%= for {beginning_of_week, times} <- @data do %>
  <table class="table table-striped">
    <caption>
      <h4>Week starting
        <%= beginning_of_week |> Timex.format!("{D} {Mfull} {YYYY}") %>
      </h4>
    </caption>
    <thead>
      <tr>
        <th>Person</th>
        <%= for day_offset <- 0..6 do %>
          <%
            day = Timex.shift(beginning_of_week, days: day_offset)
          %>
          <th class="text-right"><%= day |> Timex.format!("{WDshort} {D}")%>
        <% end %>
        <th class="text-right">Hours</th>
        <th class="text-right">Days</th>
      </tr>
    </thead>
    <tbody>
      <%= for {person, person_times} <- Enum.group_by(times, &elem(&1, 1)) do %>
        <tr>
          <td><%= link(person.name, to: person_path(@conn, :show, person.slug)) %></td>
          <%= for {day, hours} <- daily_hours(beginning_of_week, person_times) do %>
            <%= if hours == 0 do %>
              <td class="text-right" style="color: #ccc;">
                <%=
                  link "-", to: entry_path(@conn, :new, %{
                    "entry" => %{
                      "person_id" => person.id,
                      "project_id" => @project.id,
                      "date" => to_string(day),
                    }
                  })
                %>
              </td>
            <% else %>
              <td class="text-right" style="color: #444;">
                <%= hours %>
              </td>
            <% end %>
          <% end %>
          <td class="text-right">
            <strong>
              <%= calculate_totals(person_times) %>
            </strong>
          </td>
          <td class="text-right">
            <strong>
              <%= calculate_days(person_times) %>
            </strong>
          </td>
        </tr>
      <% end %>
    </tbody>
    <tfoot>
      <tr class="warning">
        <th>Total</th>
        <%= for {_, hours} <- daily_hours(beginning_of_week, times) do %>
          <%= if hours == 0 do %>
            <th class="text-right" style="color: #ccc;">
              -
            </th>
          <% else %>
            <th class="text-right" style="color: #444;">
              <%= hours %>
            </th>
          <% end %>
        <% end %>
        <th class="text-right">
          <%= calculate_totals(times) %>
        </th>
        <th class="text-right">
          <%= calculate_days(times) %>
        </th>
      </tr>
    </tfoot>
  </table>
<% end %>

lib/timerobot/web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <link rel="apple-touch-icon-precomposed" sizes="57x57" href="images/apple-touch-icon-57x57.png" />
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="images/apple-touch-icon-114x114.png" />
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="images/apple-touch-icon-72x72.png" />
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="images/apple-touch-icon-144x144.png" />
    <link rel="apple-touch-icon-precomposed" sizes="60x60" href="images/apple-touch-icon-60x60.png" />
    <link rel="apple-touch-icon-precomposed" sizes="120x120" href="images/apple-touch-icon-120x120.png" />
    <link rel="apple-touch-icon-precomposed" sizes="76x76" href="images/apple-touch-icon-76x76.png" />
    <link rel="apple-touch-icon-precomposed" sizes="152x152" href="images/apple-touch-icon-152x152.png" />
    <link rel="icon" type="image/png" href="images/favicon-196x196.png" sizes="196x196" />
    <link rel="icon" type="image/png" href="images/favicon-96x96.png" sizes="96x96" />
    <link rel="icon" type="image/png" href="images/favicon-32x32.png" sizes="32x32" />
    <link rel="icon" type="image/png" href="images/favicon-16x16.png" sizes="16x16" />
    <link rel="icon" type="image/png" href="images/favicon-128.png" sizes="128x128" />
    <meta name="application-name" content="&nbsp;"/>
    <meta name="msapplication-TileColor" content="#FFFFFF" />
    <meta name="msapplication-TileImage" content="mstile-144x144.png" />
    <meta name="msapplication-square70x70logo" content="mstile-70x70.png" />
    <meta name="msapplication-square150x150logo" content="mstile-150x150.png" />
    <meta name="msapplication-wide310x150logo" content="mstile-310x150.png" />
    <meta name="msapplication-square310x310logo" content="mstile-310x310.png" />

    <title>Timerobot</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <%= render "_header.html", assigns %>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div>
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>